[package]
name = "toy_game_engine"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
raylib = "5.0.2"

[profile.release]
opt-level = 3
codegen-units = 1
lto = "fat"
panic = "abort"
strip = true
